---
abstract: 'Text pipes that can encode and decode HTML entities'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe-HTML
provides:
  Text::Pipe::HTML:
    file: lib/Text/Pipe/HTML.pm
    version: 1.100880
  Text::Pipe::HTML::DecodeEntities:
    file: lib/Text/Pipe/HTML/DecodeEntities.pm
    version: 1.100880
  Text::Pipe::HTML::EncodeEntities:
    file: lib/Text/Pipe/HTML/EncodeEntities.pm
    version: 1.100880
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  HTML::Entities: 0
  Scalar::Util: 0
  Test::More: 0.88
  Text::Pipe: 0
  Text::Pipe::Base: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Pipe-HTML
  homepage: http://search.cpan.org/dist/Text-Pipe-HTML/
  repository: http://github.com/hanekomu/Text-Pipe-HTML
version: 1.100880
